### ISSUE TITLE
Syntax error when using php 5.3.10 

### ISSUE THREAD

**Issue by dajjen** [jhedstrom/DrupalDriver#28] opened 2015-03-30 08:42 UTC
I'm using drupal extension and the requirement is PHP 5.3.5 (http://behat-drupal-extension.readthedocs.org/en/3.0/requirements.html) but i get something like:

<code>
Parse error: syntax error, unexpected '[' in .../vendor/drupal/drupal-driver/src/Drupal/Driver/Cores/Drupal6.php on line 416
</code>

This is becauseof the short array syntax, that 5.3.10 don't allow (I think).

**Comment by jhedstrom** [comment] 2015-03-30 22:17
The problem is that many dependent libraries (eg, Goutte requires Guzzle, which requires React) are now moving to 5.4 only support. I'll need to essentially document a `composer.lock` file for folks to use if they need PHP 5.3 support.

**Comment by jhedstrom** [comment] 2015-03-30 22:46
Sorry, I misread the actual error here. I'm seeing the issue I mentioned above elsewhere--this issue is specific to code in this repo :)

**Closed** 2015-03-30 23:13 UTC

**Comment by dajjen** [comment] 2015-03-31 06:41
ok I get that, but in that case maybe you should change the requirement in the documentation http://behat-drupal-extension.readthedocs.org/en/3.0/requirements.html

**Comment by dajjen** [comment] 2015-03-31 06:42
And thanks again for this code, it.s great!
